package com.bdqn.bbh_zy.mapper;

import com.bdqn.bbh_zy.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbh_user_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbh_user_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);
}