
server:
  port: 8080

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/bbh?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: 6666
    driver-class-name: com.mysql.jdbc.Driver

#注意格式不要改，多空格少空格不行
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp


mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.bdqn.bbh_zy.entity  # 注意：对应实体类的路径


pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
    level:
      com.bdqn.bbh_zy.mapper: debug
      com.bdqn.bbh_zy.Interceptor: info