package com.bdqn.bbh_zy.entity;

import java.math.BigDecimal;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.waterMoney
     *
     * @mbggenerated
     */
    private BigDecimal watermoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.electricMoney
     *
     * @mbggenerated
     */
    private BigDecimal electricmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.face
     *
     * @mbggenerated
     */
    private String face;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.size
     *
     * @mbggenerated
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.square
     *
     * @mbggenerated
     */
    private BigDecimal square;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.id
     *
     * @return the value of bbh_room_room.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.id
     *
     * @param id the value for bbh_room_room.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.number
     *
     * @return the value of bbh_room_room.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.number
     *
     * @param number the value for bbh_room_room.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.waterMoney
     *
     * @return the value of bbh_room_room.waterMoney
     *
     * @mbggenerated
     */
    public BigDecimal getWatermoney() {
        return watermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.waterMoney
     *
     * @param watermoney the value for bbh_room_room.waterMoney
     *
     * @mbggenerated
     */
    public void setWatermoney(BigDecimal watermoney) {
        this.watermoney = watermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.electricMoney
     *
     * @return the value of bbh_room_room.electricMoney
     *
     * @mbggenerated
     */
    public BigDecimal getElectricmoney() {
        return electricmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.electricMoney
     *
     * @param electricmoney the value for bbh_room_room.electricMoney
     *
     * @mbggenerated
     */
    public void setElectricmoney(BigDecimal electricmoney) {
        this.electricmoney = electricmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.face
     *
     * @return the value of bbh_room_room.face
     *
     * @mbggenerated
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.face
     *
     * @param face the value for bbh_room_room.face
     *
     * @mbggenerated
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.size
     *
     * @return the value of bbh_room_room.size
     *
     * @mbggenerated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.size
     *
     * @param size the value for bbh_room_room.size
     *
     * @mbggenerated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.square
     *
     * @return the value of bbh_room_room.square
     *
     * @mbggenerated
     */
    public BigDecimal getSquare() {
        return square;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.square
     *
     * @param square the value for bbh_room_room.square
     *
     * @mbggenerated
     */
    public void setSquare(BigDecimal square) {
        this.square = square;
    }
}