package com.bdqn.bbh_zy.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_user_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_user_user.roomId
     *
     * @mbggenerated
     */
    private Integer roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_user_user.roleId
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_user_user.classId
     *
     * @mbggenerated
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_user_user.realName
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_user_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_user_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_user_user.telephone
     *
     * @mbggenerated
     */
    private Integer telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_user_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_user_user.id
     *
     * @return the value of bbh_user_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_user_user.id
     *
     * @param id the value for bbh_user_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_user_user.roomId
     *
     * @return the value of bbh_user_user.roomId
     *
     * @mbggenerated
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_user_user.roomId
     *
     * @param roomid the value for bbh_user_user.roomId
     *
     * @mbggenerated
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_user_user.roleId
     *
     * @return the value of bbh_user_user.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_user_user.roleId
     *
     * @param roleid the value for bbh_user_user.roleId
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_user_user.classId
     *
     * @return the value of bbh_user_user.classId
     *
     * @mbggenerated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_user_user.classId
     *
     * @param classid the value for bbh_user_user.classId
     *
     * @mbggenerated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_user_user.realName
     *
     * @return the value of bbh_user_user.realName
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_user_user.realName
     *
     * @param realname the value for bbh_user_user.realName
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_user_user.name
     *
     * @return the value of bbh_user_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_user_user.name
     *
     * @param name the value for bbh_user_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_user_user.password
     *
     * @return the value of bbh_user_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_user_user.password
     *
     * @param password the value for bbh_user_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_user_user.telephone
     *
     * @return the value of bbh_user_user.telephone
     *
     * @mbggenerated
     */
    public Integer getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_user_user.telephone
     *
     * @param telephone the value for bbh_user_user.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_user_user.email
     *
     * @return the value of bbh_user_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_user_user.email
     *
     * @param email the value for bbh_user_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}